### ISSUE TITLE
badge for private repos?

### ISSUE THREAD

**Issue by pabl-o-ce** [badgen/badgen.net#165]
can I create badgen for private repos...

**Comment by amio** [comment]
Nope, Badgen cannot access private repo without a token.

Maybe you can consider creating an endpoint (with [/runkit](https://badgen.net/docs/runkit) or [/https](https://badgen.net/docs/https)), get data privately and return a json data, let Badgen do the svg generating.

**Comment by sumitkanoje** [comment]
Does someone give an example of creating an endpoint (with /runkit or /https)?

**Comment by amio** [comment]
@sumitkanoje there's some doc with examples:

https://badgen.net/docs/https
https://badgen.net/docs/runkit

**Comment by sumitkanoje** [comment]
@amio I'm not aware of which link/api to be consumed inside for fetching build status for private repo, Should it be github or circleci ?

**Comment by amio** [comment]
@sumitkanoje Yep, you should make a public api, which get raw status from github/circleci and response with `{ subject, status, color }`, Badgen will render a badge from that api.
