### ISSUE TITLE
fontawesome icons

### ISSUE THREAD

**Issue by diomed** [badgen/badgen.net#277]
would be great if all fontawesome icons could be used somehow

**Comment by amio** [comment]
Hmm, maybe we can use `<image />` in svg to embed **any image** as icon
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_Image_Tag

**Comment by amio** [comment]
Experimental support for external icon, it works fine when open in browser directly, while breaks as inline image 🤦‍♂️

- https://badgen.net/badge/icon/paypal?icon=https://simpleicons.now.sh/icons/paypal.svg%3Fcolor=FFF&label
- ![](https://badgen.net/badge/icon/paypal?icon=https://simpleicons.now.sh/icons/paypal.svg%3Fcolor=FFF&label)

**Comment by amio** [comment]
We can use external icon now 🎉

https://badgen.net/badge/icon/paypal?icon=https://simpleicons.now.sh/icons/paypal.svg?color=FFF&label
![](https://badgen.net/badge/icon/paypal?icon=https://simpleicons.now.sh/icons/paypal.svg?color=FFF&label)
