### ISSUE TITLE
custom text generator?

### ISSUE THREAD

**Issue by diomed** [badgen/badgen.net#278]
shields.io has custom text generator on their page.
would something like this be possible for badgen as well?

**Comment by amio** [comment]
Seems this related to #212 and #192

**Comment by amio** [comment]
Now the builder is out https://badgen.net/builder

**Comment by diomed** [comment]
@amio below guidelines shouldn't disappear

**Comment by diomed** [comment]
does builder support font awesome icons?

**Comment by amio** [comment]
> guidelines below shouldn't disappear

The plan is to show hints dynamically, base on [schemes](https://badgen.net/docs/npm), and provide md/html markup for copy. While I'm not decided the final UX, PR's welcome too 👏

> does builder support font awesome icons?

It support external icon, for example:
https://badgen.net/builder#badge/Swift/4.2/orange?icon=https://simpleicons.now.sh/icons/swift.svg?color=fa7343

As long as you have a icon link like
https://simpleicons.now.sh/icons/swift.svg?color=fa7343
