### ISSUE TITLE
sections

### ISSUE THREAD

**Issue by diomed** [badgen/badgen.net#279]
could you make possible multiple colored badges, colored per our choice?

like - why would first always have to be black?

lets say - first section could be red - 2nd white - third blue [why limit them to 2 sections, when we could have more - longer - up to 4 or 5]

**Comment by amio** [comment]
Interesting idea, what would you use 3 sections badge for?

**Comment by diomed** [comment]
mode data of course.
text would vary.

**Comment by amio** [comment]
I think badgen.net doesn't need this feature right now, it can goes to https://github.com/badgen/badgen

**Comment by amio** [comment]
No plan for adding this for now.

A possible workaround is to use `list` query:

- https://badgen.net/badge/sections/a,b,c?list
- https://badgen.net/badge/sections/a,b,c?list=/

**Comment by tunnckoCore** [comment]
Configurable left-side color is the one part of this issue that's cool.

**Comment by amio** [comment]
@tunnckoCore for label color, the plan is to add a light theme https://github.com/badgen/badgen.net/issues/281

**Comment by diomed** [comment]
you could incorporate this: https://github.com/Simonwep/pickr
