### ISSUE TITLE
Add a style/theme for light and dark mode

### ISSUE THREAD

**Issue by styfle** [badgen/badgen.net#281]
The current style of the left side of each badge is dark.

I am proposing an option for a light style or theme.

This would look good for badges like Jest or TypeScript. [![jest](https://jestjs.io/img/jest-badge.svg)](https://github.com/facebook/jest)

Also note the color of the logo matches the color of the right side.

This could be implemented with a new query string parameter `style=light` or `style=dark` or perhaps `theme=light`.

Relevant discussion here: https://github.com/badgen/badgen-icons/pull/12#issuecomment-495962286

**Comment by amio** [comment]
This might goes with or after [v2](https://github.com/badgen/badgen.net/pull/282) 😉

**Comment by amio** [comment]
`labelColor` supported now (so we don't need to design a dark theme :D)

![](https://badgen.net/badge/purple/lamborghini/cyan?labelColor=purple)
https://badgen.net/badge/purple/lamborghini/cyan?labelColor=purple
