### ISSUE TITLE
Support FOSSA and Dependabot

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen.net#283]
# @Dependabot has 2 badges. 

One is for status, which I believe is working and dynamic (not like the Renovate's one yet)

```
https://api.dependabot.com/badges/status?host=github&repo=tunnckoCore/asia
```
![](https://api.dependabot.com/badges/status?host=github&repo=tunnckoCore/asia)

```
https://api.dependabot.com/badges/status?host=github&repo=tunnckoCore/babel-preset-esmc
```
![](https://api.dependabot.com/badges/status?host=github&repo=tunnckoCore/babel-preset-esmc)

Another one is the so-called `compatibility` score badge, but... I'm guessing it's too dynamic.

```
[![Dependabot compatibility score](https://api.dependabot.com/badges/compatibility_score?dependency-name=lodash&package-manager=npm_and_yarn&previous-version=4.17.10&new-version=4.17.11)](https://dependabot.com/compatibility-score.html?dependency-name=lodash&package-manager=npm_and_yarn&previous-version=4.17.10&new-version=4.17.11)
```

results in [![Dependabot compatibility score](https://api.dependabot.com/badges/compatibility_score?dependency-name=lodash&package-manager=npm_and_yarn&previous-version=4.17.10&new-version=4.17.11)](https://dependabot.com/compatibility-score.html?dependency-name=lodash&package-manager=npm_and_yarn&previous-version=4.17.10&new-version=4.17.11) see the page to which it leads [here](https://dependabot.com/compatibility-score/?dependency-name=lodash&package-manager=npm_and_yarn&previous-version=4.17.10&new-version=4.17.11).

_(I definitely don't like Dependabot and don't want to support and embrace its usage, but here... why not... ;d)_

---

# As about the FOSSA

It has a passing/failing badge like this, and supports github bitbucket gitlab?

```
[![FOSSA Status](https://app.fossa.io/api/projects/git%2Bgithub.com%2FtunnckoCoreLabs%2Fparse-function.svg?type=shield)](https://app.fossa.io/projects/git%2Bgithub.com%2FtunnckoCoreLabs%2Fparse-function?ref=badge_shield)
```

[![FOSSA Status](https://app.fossa.io/api/projects/git%2Bgithub.com%2FtunnckoCoreLabs%2Fparse-function.svg?type=shield)](https://app.fossa.io/projects/git%2Bgithub.com%2FtunnckoCoreLabs%2Fparse-function?ref=badge_shield)

**Comment by amio** [comment]
Dependabot is going to support flat style officially (https://github.com/dependabot/feedback/issues/6#issuecomment-495940146)

About FOSSA, I'm not familiar with it, but it seems we can create a lot badges for it 😆

**Comment by amio** [comment]
Tried with FOSSA, looks like it's all about license, and they have done a good job on prompting their badge https://github.com/badgen/badgen/pull/55

I think there's no need to replicate their badge to badgen.net 🤔

**Comment by tunnckoCore** [comment]
It may not be the place you want it. Also, if you need to do it manually it requires encoding and etc. Badgen url is more clean and stay in line with your other badges.

**Comment by amio** [comment]
Indeed, their url is terrible.
