### ISSUE TITLE
Support Now CI badge

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen.net#286]
It might sounds crazy, but it's truly beautiful to use it as CI/CD :D 

**How?**

`now.json`

```json
{
  "version": 2,
  "name": "tunnckocore-template",
  "builds": [{ "src": "package.json", "use": "@now/static-build" }]
}
```

and define `now-build` script

```json
"scripts": {
  "lint": "yarn scripts devest lint",
  "test": "yarn scripts devest test",
  "build": "yarn scripts pika-pack build --out dist",
  "status:pass": "badgen --subject build --status passing --color green > dist/badge.svg",
  "status:fail": "badgen --subject build --status failing --color red > dist/badge.svg",
  "pkg": "yarn lint && yarn test && yarn build",
  "now-build": "(yarn pkg && yarn status:pass) || yarn status:fail"
},
```

The thing is, that when build fails, it actually doesn't publish the contents of `dist/` so we can't just get the generated `failing` badge. For now I can just point the badge to [`https://<myrepo>.<my-zeit-username>.now.sh/badge.svg`](https://tunnckocore-template-o7lok123v.now.sh/badge.svg) ![](https://tunnckocore-template-o7lok123v.now.sh/badge.svg)

So, the alternatively we can have it here, and ~~query directly the API with https://zeit.co/docs/api#endpoints/deployments/list-deployments and get the first item from the `data.deployments[0].state`~~ We'll need the deployment "name" and fitler by it and after that get the first item. But, sadly, the API endpoint wants a token, which might be a problem, because we also have some rate limits there. But we have caching here, right? So it won't be a problem?

I can PR, but we'll need to add a token to the secrets.

**Comment by tunnckoCore** [comment]
Pretty cool and small implementation, that's why I love badgen... :D

```js
const axios = require('axios');

async function nowci(name) {
  const { data } = await axios({
    method: 'GET',
    url: 'https://api.zeit.co/v4/now/deployments',
    headers: {
      authorization: 'Bearer XXXX',
    },
  });

  const builds = data.deployments.filter(
    (x) => x.name === 'tunnckocore-template',
  );

  console.log(builds[0].state);
}

nowci('tunnckocore-template');
```

**Comment by styfle** [comment]
I like the idea of using ZEIT Now as a CI solution but it seems like the API is a better solution then writing a file.

You could probably make a couple API calls like [GET GET /v1/projects/:name](https://zeit.co/docs/api#endpoints/projects/get-a-single-project) and then [GET /v9/now/deployments/:id
](https://zeit.co/docs/api#endpoints/deployments/get-a-single-deployment) to get the `readyState`.

**Comment by tunnckoCore** [comment]
Yea, but still needs a token anyway. Also why to make 2 API calls instead of one?

**Comment by tunnckoCore** [comment]
Sweet. I'm done. How to name it, what to be the endpoint? Any preferences @styfle, @amio? Just `now` sounds... Maybe `zeit-now` or `now-ci` (with or without the dash).

**Comment by tunnckoCore** [comment]
Okay, why I don't see it on the index page? :thinking: 

/cc @amio

**Comment by tunnckoCore** [comment]
Unfortunately, there's one more limitation. Just realized that with your token you can't query other than your deployments. So, we'll need to require passing a token for now. Or give up for now.

**Comment by tunnckoCore** [comment]
Or at least, most easiest way would be to support specific `status` in the github live badge :D

**Comment by amio** [comment]
That's brilliant, almost worked 😂

+1 on the github way

**Comment by tunnckoCore** [comment]
Yea, right? :rofl: I'm a bit sad now, it was super cool, but yea through GitHub makes better sense.

**Comment by amio** [comment]
Found this github v3 endpoint (prefer to use more v3 api in github live badge, to save quota on v4):
https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref

then the schema:
```
/github/status/:owner/:repo/:ref?
```

Looks straight and simple

**Comment by tunnckoCore** [comment]
Yes, but it's for combined status, not only for the "build". And if we think of Now as CI, then we should get only its status.

**Comment by amio** [comment]
Despite the name "combined", this api actually provided separated statuses :D
https://api.github.com/repos/zeit/now-cli/status/master

If we support detailed status, the schema could be:

```
/github/status/:owner/:repo/:ref?
/github/status/:owner/:repo/:ref/:context
```

**Comment by tunnckoCore** [comment]
Yup.

**Comment by amio** [comment]
@tunnckoCore I can work on this now 😉

**Comment by amio** [comment]
Just realize that we already have the combined status badge 😂
with exactly this schema:

```
/github/:topic<status>/:owner/:repo/:ref?
```

- https://badgen.net/github/status/micromatch/micromatch
- https://badgen.net/github/status/micromatch/micromatch/gh-pages 
- https://badgen.net/github/status/micromatch/micromatch/f4809eb6df80b

**Comment by amio** [comment]
It's live now

https://badgen.net/github/status/zeit/now-cli/master/ci/circleci:%20test-unit
![](https://badgen.net/github/status/zeit/now-cli/master/ci/circleci:%20test-unit)

https://badgen.net/github/status/zeit/now-cli/master/ci/circleci:%20test-integration
![](https://badgen.net/github/status/zeit/now-cli/master/ci/circleci:%20test-integration)

**Comment by tunnckoCore** [comment]
Cool. But still, how you can get the whole combined status of circle ci for example? :D Cuz, what I'm seeing now is that you need to define `test-unit`, `test-integration` and etc. In case of Now it will be `now`, `now/package.json`, and even worse in monorepo scenario :D 

Maybe adding query param `?combined` would fix this.

like

https://badgen.net/github/status/zeit/now-cli/master/ci/circleci?combine=true

**Comment by amio** [comment]
We can omit the `combined=true`, just

```
/github/status/zeit/now-cli/master/ci/circleci
```

will combine all statuses starting with `ci/circleci`.

While the problem is, how do we show mixed status? for statuses `success` + `error` + `pending` , some options:

1. ![](https://badgen.net/badge/ci%2Fcircleci/fail/red)
2. ![](https://badgen.net/badge/ci%2Fcircleci/success,error,pending/grey?list)
3. ![](https://badgen.net/badge/ci%2Fcircleci/mixed/grey)

(1) needs explaining, (2) is ugly, and ambiguous, (3) needs a better wording.

Before we have a nice solution for this, I think the workaround for now is, use a final job as the "combined" status badge, like `ci/circleci: coverage` for `now-cli`'s case.

**Comment by amio** [comment]
Overall, I guess the default combined status would be fine to use on most project homepage, the separated status badge could be used on some dashboard/badgeboard like
https://react-component.github.io/badgeboard/

**Comment by tunnckoCore** [comment]
> While the problem is, how do we show mixed status

Just if it is failing show `failure`, if it is `pending` it will anyway go to one of the other states, so no need to show.

```js
const failure = circleci.find(x => x.state === 'failure')
const pending = circleci.find(x => x.state === 'pending')
const state = failure ? 'failure' : (pending ? 'pending' : 'success')

return {
  subject: state
}
```

**Comment by amio** [comment]
If it's `pending` with `success`, I think it should display `pending`, so:

- `failure`/`error` + anything = `failure`
- `pending`s + `success`s = `pending`
- `success`s = `success`

But no matter how we define the final status, it's opinionated, we need to explain how we generated the final status，which is what I want to avoid.

**Comment by tunnckoCore** [comment]
> If it's pending with success

Yes, of course, in above example `circleci` is just an array of all circleci statuses.

> But no matter how we define the final status, it's opinionated

It's not. It's logical and intuitive. Every human being, or at least developer will think this way, since it's the same as `if true && false` resulting in the `else` state.

**Comment by amio** [comment]
Hmm, I just thought about that, this won't break anything we already have, it's an enhancement, and it's simple enough. Just like the empty `icon` param, we never promote it, but it's there, and it's handy.

@tunnckoCore would you make a PR for this?

**Comment by tunnckoCore** [comment]
Okay, I'll try.

**Comment by tunnckoCore** [comment]
Do you have some example repo in mind that has some circleci failing? I can't remember some of mine.

**Comment by tunnckoCore** [comment]
Doh, I can't get it working with my github tokens? I've seen the GH_TOKEN**S** but seems it not works. I also tried to put my token directly where's the request but it still shows `token required`?

**Comment by tunnckoCore** [comment]
Do you have Now enabled here for PRs? It seems not?

**Comment by tunnckoCore** [comment]
I'll put this comment here, just to not be inside the code, okay? :D 

Example repo http://localhost:3000/github/status/zeit/hyper
  
  commit 1: 34fb41c23b
  - Combined GitHub status - failing, because appveyor pr
  - http://localhost:3000/github/status/zeit/hyper/34fb41c23b

  - Combined CircleCI status - passing
  - http://localhost:3000/github/status/zeit/hyper/34fb41c23b/ci/circleci

  - Single CircleCI status - passing
  - http://localhost:3000/github/status/zeit/hyper/34fb41c23b/ci/circleci:%20build

  - Single Appveyor status - passing
  - http://localhost:3000/github/status/zeit/hyper/34fb41c23b/continuous-integration/appveyor/branch

  - Single Appveyor status - failing
  - http://localhost:3000/github/status/zeit/hyper/34fb41c23b/continuous-integration/appveyor/pr

  - Combine Appveyor status - failing
  - two possibilities (because we are check with .startsWith)
  - http://localhost:3000/github/status/zeit/hyper/34fb41c23b/continuous-integration/appveyor
  - http://localhost:3000/github/status/zeit/hyper/34fb41c23b/continuous-integration

  commit 2: efeedd0a9d3
  - Combined GitHub status - failing

  - Single CircleCI status - passing
  - http://localhost:3000/github/status/zeit/hyper/efeedd0a9d3/ci/circleci:%20build

  - Combined Circle status - failing
  - http://localhost:3000/github/status/zeit/hyper/efeedd0a9d3/ci/circleci

  - Combined Travis status - failing
  - http://localhost:3000/github/status/zeit/hyper/efeedd0a9d3/continuous-integration/travis-ci

  - Combined Travis and Appveyor status - failing
  - cool bonus...
  - http://localhost:3000/github/status/zeit/hyper/efeedd0a9d3/continuous-integration

  - Single Appveyor status - passing
  - http://localhost:3000/github/status/zeit/hyper/efeedd0a9d3/continuous-integration/appveyor
