### ISSUE TITLE
Fallback to the original npm registry (or jsdelivr) when unpkg fail

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen.net#292]
For couple of hours I got error 500. First noticed that a ton of badges are just broken on ton of repos. So then I tried to create new project (for which I use mine `charlike` scaffolder which is again using the unpkg registry too) it turns out that unpkg returns 500 for non-cached packages (which is still strange cuz it should have mine pacakges already cached, but probably some cache invalidation happen in recent months).

So, we need to handle this case and fallback to some more reliable source of truth. I bet on jsdelivr, cuz as we know the npm registry sucks a bit.

**Comment by tunnckoCore** [comment]
It turns out that it's even more freaking, because all of my fully automated publishing and releasing is based on the `unpkg.com`, by the `@tunnckcore/package-json` package. The irony is that I cannot even update it, because the publish/release tool uses it. So, the only way is to manually publish a patch. Or, to patch the `charlike` locally on my machine.

**Comment by amio** [comment]
Switched to jsdelivr now, let's see if it's more stable.

**Comment by amio** [comment]
Just found this https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#abbreviated-metadata-format

Let's fix npm version badge once and for all!
