### ISSUE TITLE
Is it possible to support commits and PR badges for GitLab?

### ISSUE THREAD

**Issue by rn4n** [badgen/badgen.net#297]
Hello.

Is it possible to support more GitLab related badges? The same way it's done for GitHub, for example:

<div align='center'>
<img src='https://user-images.githubusercontent.com/3982052/61206387-cd53c500-a6c8-11e9-9858-7f9b08b90115.png'>
</div>

**Comment by amio** [comment]
Sure it's possible, PR's welcome :D

Seems GitLab serves a different set of statuses
https://docs.gitlab.com/ee/api/README.html

**Comment by reebr** [comment]
@amio nice.
I'd like to work on this issue. But I will take time to understand the structure of the project and actually contribute. It is a problem?

**Comment by amio** [comment]
@reebr Not a problem :D

**Comment by reebr** [comment]
The graphql resource of GitLab does not provide the repository information correctly.
Maybe it's necessary to do a "mix " of the Rest API with Graphql to get the data needed.

Ref: https://gitlab.com/gitlab-org/gitlab-ce/issues/65170

**Comment by amio** [comment]
That's fine, we are using rest & graphql api in GitHub badge (to double the [rate limit](https://developer.github.com/v3/rate_limit/#understanding-your-rate-limit-status))

**Comment by alexnaiman** [comment]
Hello guys! I've seen that @rn4n had removed their assignment, so I would like to give it a try and make a PR in the future with this feature. If it is alright, please, assign it to me @amio 😄

**Comment by amio** [comment]
Sure, thanks! @alexnaiman
