### ISSUE TITLE
Github Actions (CI/CD) badge

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen.net#304]
Seems like Github already have a badge at 

```
https://github.com/<user>/<repo>/workflows/<workflow name>/badge.svg
```

https://github.com/actions/toolkit/workflows/Main%20workflow/badge.svg

![](https://github.com/actions/toolkit/workflows/Main%20workflow/badge.svg)

But as we know, our badges are better :P

**Comment by amio** [comment]
Yep, let's do it!

**Comment by amio** [comment]
I guess we could look up in api docs
https://developer.github.com/v4/
https://developer.github.com/v3/

But I didn't found anything for new actions/workflows

**Comment by tunnckoCore** [comment]
Just found that it's available through the CheckRuns api.

```js
const endpoint = "repos/:user/:repo/commits/master/check-runs"

fetch(endpoint, {
  headers: {
    Accept: 'application/vnd.github.antiope-preview+json'
  }
}).then(async (res) => {
  console.log(await res.json())
  /*
  {
    ...stuff
    check_runs: [check],
    total_count: 5
  }

  // the Check object
  {
    // ...stuff
    app: { name: 'GitHub Actions', slug: 'github-actions', other },
    conclusion: 'success',
    head_sha: '570a918ea31272e7128c51aeeb395ed407c3127b',
    name: 'test (macos-latest, 12.x)',
    status: 'completed',
  }
  */
})
```

We should start from here. :D
