### ISSUE TITLE
Confused about how to use GitHub Actions status badges

### ISSUE THREAD

**Issue by brandonweiss** [badgen/badgen.net#305]
Hey! I just recently got access to GitHub Actions, started using it for CI, and wanted to switch my Travis badge to a GitHub Action status badge.

The template is:

`/github/status/:owner/:repo/:ref/:context+`

And some examples of a “single action status” are:

`/github/status/facebook/react/master/ci/circleci:%20lint`
![](https://badgen.net/github/status/facebook/react/master/ci/circleci:%20lint)

`/github/status/facebook/react/master/coverage/coveralls`
![](https://badgen.net/github/status/facebook/react/master/coverage/coveralls)

I’m not really sure what “context” is, but pattern matching on the examples I assume it must be the action name. In my case that’s `Continuous Integration`. So I tried this:

`/github/status/brandonweiss/charge/master/Continuous%20Integration`
![](https://badgen.net/github/status/brandonweiss/charge/master/Continuous%20Integration)

And it worked! But I’m always suspicious of when something works the first time… so I tried a non-existent action name:

`/github/status/brandonweiss/charge/master/foobar`
![](https://badgen.net/github/status/brandonweiss/charge/master/foobar)

And it also worked 😞 Is it broken? Or am I mis-using it?

**Comment by amio** [comment]
😆 Should get fixed in bd4483cb836a0d42dd68ba099237b6e00985cfd5

**Comment by brandonweiss** [comment]
@amio Thank you! ❤️

**Comment by tunnckoCore** [comment]
"Context" is part of the Status object that GitHub returns.

https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref

Context is the name of the service, usually. It's very easy to know what you need by checking the names in the commit status checks. For CircleCI it's `ci/circleci: <name of job>`, for Travis it's `continuous-integration/travis-ci/push`, for Appveyor `continuous-integration/appveyor/push`, for CodeCov it's `codecov/patch`, for Jenkins it may be `continuous-integration/jenkins` and so on.

So here, how it was working (as I implemented it and just seen that it's completely changed) was by testing the `context.includes(val)` where `val` is the incoming from the url. That allowed to have cool combinations, for example status badge for both Travis and AppVeryor but not including the Circle and CodeCov ones.
