### ISSUE TITLE
Advertising package

### ISSUE THREAD

**Issue by traverseda** [badgen/badgen.net#308]
It looks like this project depends on https://github.com/feross/funding, a project intended to show advertising in a projects build log.

I'm not familiar with your project, I'm just looking through a list of projects that depend on `feross/funding`. It's my understanding that right now there aren't any advertising messages actually showing, but if you're uncomfortable with the possibility of advertisements in build logs that's something you might want to look into.

**Comment by amio** [comment]
@traverseda Thanks for reminding!

Since [standard@4.1.0](https://github.com/standard/standard/blob/master/CHANGELOG.md#1410---2019-08-28) has removed the funding package, going to update standard then. :)
