### ISSUE TITLE
Feature: query param `size` (probably only for the flat mode)

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen.net#309]
So we can have bigger badges, like https://forthebadge.com/

**Comment by amio** [comment]
Sounds interesting, it would be easier to implement with `scale`.

**Comment by tunnckoCore** [comment]
Oh yea, probably better word.

**Comment by amio** [comment]
Looks cool!

`https://flat.badgen.net/badge/badgen/net?scale=2`
![](https://flat.badgen.net/badge/badgen/net?scale=2)
