### ISSUE TITLE
GitHub actions status incorrect?

### ISSUE THREAD

**Issue by brandonweiss** [badgen/badgen.net#310]
I think something is up with GitHub Actions statuses but I can’t tell what…

I have a “[Tests](https://github.com/brandonweiss/charge/actions)” action. The badge should be this:

https://badgen.net/github/status/brandonweiss/charge/master/Tests
![](https://badgen.net/github/status/brandonweiss/charge/master/Tests)

It was working but now it’s returning “unknown”. Strangely, here’s what happens if I lop off the action name:

https://badgen.net/github/status/brandonweiss/charge/master
![](https://badgen.net/github/status/brandonweiss/charge/master)

It says “pending” even though nothing is pending as far as I can tell 🤔

I can’t tell if this an issue on the Badgen side or if GitHub broke something?

**Comment by amio** [comment]
Now [this api](https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref) do returns a `pending` status, and empty `statuses` list:
https://api.github.com/repos/brandonweiss/charge/commits/master/status

I guess it's related to GitHub's new Action implementation. Does it ever working after you upgrade to Actions V2?

**Comment by brandonweiss** [comment]
I just started using GitHub Actions a few weeks ago, so I think I’ve always been on V2?

Yeah, it was working when I started using the badge, but I just noticed it broke a few days ago.

**Comment by tunnckoCore** [comment]
It's not meant to work for Actions without problems, I guess.

That's why I opened #304 for actions badges.

@amio, that's one of the reasons why naming and docs are important part of anything, haha. This `combined action status` on the docs is misleading. It's not an action, it's a status context (a state of a context) and I still believe we should rename it to be consistent with the GitHub API.

https://github.com/badgen/badgen.net/pull/289/commits/cb1844e71d5c6c6f6448cad052715245b2483042

**Comment by tunnckoCore** [comment]
The thing is that it's pending because if it find even only one pending status in the all array of contexts of statuses, it will show pending. And that's correct behavior. You can [see it here](https://github.com/badgen/badgen.net/blob/master/endpoints/github.ts#L118).

**Comment by tunnckoCore** [comment]
Okay, I think it's some bug with the GitHub API. It basically returns empty array of `statuses`.

This also responses with `pending` but there was never pending state there and is green all the time... https://api.github.com/repos/tunnckocorehq/hela/commits/v3-next/status

**Comment by amio** [comment]
> that's one of the reasons why naming and docs are important part of anything

@tunnckoCore Absolutely :D 

"combined action status" seems fine when GitHub just roll out Actions V1, but totally not OK in Actions V2 age.
