### ISSUE TITLE
npm badge show wrong version of latest tag

### ISSUE THREAD

**Issue by afc163** [badgen/badgen.net#311]
```
https://flat.badgen.net/npm/v/antd?icon=npm
```

![](https://flat.badgen.net/npm/v/antd?icon=npm)

**This should be 3.24.3**: https://www.npmjs.com/package/antd

<img width="408" alt="image" src="https://user-images.githubusercontent.com/507615/65654969-115e3100-e04d-11e9-87fd-6ee4f5c57f17.png">

**Comment by amio** [comment]
Strange, it's `3.23.4` to me at this moment, and `npm v antd` reported:

```
antd@3.23.4 | MIT | deps: 52 | versions: 446
```

**Comment by afc163** [comment]
Fixed..maybe a cdn problem.
