### ISSUE TITLE
Move to Now v2 and `api/`

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen.net#314]
And why PRs don't have `now` activated? For the same reason?

There's no way to have some preview url, e.g. #313 cannot be seen.

I think every endpoint can be moved to the `api` folder, also use @middyjs or such to plug the `badgenServe` and etc. Actually I think Middy doesn't support async/await functions, which Now Platform supports and which supports TS out of the box too. Just write your API in TS.

**Comment by amio** [comment]
Badgen stick to Now V1 because of [expenses](https://github.com/badgen/badgen.net/pull/282#issuecomment-499736883). There's a `now-v2.json` for deploying to Now V2, the default `now.json` is for V1.

This repo is under `badgen` org on github, while the service is deployed with my zeit account. My zeit account is on Now V1 plan, while the `badgen` account on zeit is V2 free plan. Since the default `now.json` is for V1, so 🤷‍♂️

@tunnckoCore For the middleware idea, are you intent to compose badgen service with others? I've think about make `badgen-service` a standalone package, for creating any badgen-like services with a handler file like `endpoints/github.ts`.

**Comment by tunnckoCore** [comment]
> Badgen stick to Now V1 because of expenses.

Oooh, right. Not cool :D 

> For the middleware idea, are you intent to compose badgen service with others?

No.

> For the middleware idea

Not a middleware idea, just thought you can use middy or such when moving to `api/` architecture (now v2). But anywya.

**Comment by amio** [comment]
Now App will complain every commit on master and mark it as failed 😢
https://github.com/badgen/badgen.net/commit/a8f71db4ae27a430526c70db886ef3c87eeb9cf8#commitcomment-35641544

**Comment by tunnckoCore** [comment]
Yup, I've seen that too... ;/

**Comment by amio** [comment]
@tunnckoCore I guess we can make a better donation promotation, plus the Now V1 model & pricing is pretty nice for a service like Badgen. Badgen serves a stable throughput, fits better in a long running docker container than serverless fn.

**Comment by amio** [comment]
@tunnckoCore We are going to get sponsorship from ZEIT 🎉

Thanks! @styfle

**Comment by tunnckoCore** [comment]
Awww! :heart_eyes_cat:  Great! :tada:

**Comment by amio** [comment]
Done in #320

**Comment by styfle** [comment]
Do you need to deploy? Seems that badgen.net is still running v1.

**Comment by amio** [comment]
The `badgen.net` domain is under my account now, I need to transfer it to `badgen` org. If I do the remove & add operation, there will be noticable down time for two steps:
1. reconfigure the ns server to new setup (`a.zeit-world.org` etc), then get it verified with now cli
2. regenerating https certification

Is there a way to smooth this migration? @styfle

**Comment by styfle** [comment]
@amio Unfortunately, transferring domains between accounts will likely cause some downtime. I'll forward the feedback to the team so we can create a better process when moving from a personal account to a team.

**Comment by styfle** [comment]
@amio I was mistaken 😅 

This feature is available on the domains page 🎉  https://zeit.co/dashboard/domains 

- Click on the three dots on the right side of the domain
- Select the "Move" menu item
- Type in the name of the team in the modal

**Comment by amio** [comment]
@styfle Migration complete! And CD pipeline is working now https://github.com/badgen/badgen.net/commit/50d095b10cf31c1636c2527bf4f037928e497adf#commitcomment-36046247 💃

**Comment by tunnckoCore** [comment]
Great! <3 Only the readme docs need an update now, about `endpoints -> api` :)

**Comment by tunnckoCore** [comment]
And also seems like the flat endpoint is not flat :stuck_out_tongue_winking_eye:
