### ISSUE TITLE
Badgen service crashed after ce026e20

### ISSUE THREAD

**Issue by zthxxx** [badgen/badgen.net#315]
CI failed and screenshots for official website

![image](https://user-images.githubusercontent.com/15135943/67541538-da4a7080-f71b-11e9-9f4b-6e36beb80764.png)

![image](https://user-images.githubusercontent.com/15135943/67541521-cef74500-f71b-11e9-8cd3-17e92892523c.png)

![image](https://user-images.githubusercontent.com/15135943/67541561-f77f3f00-f71b-11e9-83c5-c5823de5a87a.png)

**Comment by amio** [comment]
重新部署了下 🙏
