### ISSUE TITLE
Custom badge icons

### ISSUE THREAD

**Issue by JoebRogers** [badgen/badgen.net#325]
Is there a way that I'm missing to support custom icons for badges? As far as I could tell, external badges are only supported through SimpleIcons, which isn't a solution for services with icons that aren't (and can't be) on there.

Shields.io supports custom icons through Base64 data, which is what I was using previously (and have been considering Badgen as an alternative). Is there support for this on the way at some point? Or am I missing the correct way of handling this? (Tried passing in png and svg files to the icon arg, as well as base64 just in case).

Thanks.

**Comment by tunnckoCore** [comment]
You can pass url to a SVG (only).

**Comment by JoebRogers** [comment]
Ah I see, thanks for the info. It turns out the issue I was getting where the SVG icon wasn't displaying despite being passed in the same way was an issue of hosting. I was storing the svg files in the repo and linking to them that way - looks like I needed to take the rawgit/pages approach for it to work! 

Thanks for the swift response and solution.

**Comment by kaiwu-astro** [comment]
Hi! It seems using svg link as the icon does not properly work. In your reply, the icon does not show before the "email" 

![iShot_2023-06-11_18 27 12](https://github.com/badgen/badgen.net/assets/18334656/ef538938-63ad-4ed9-8aa7-235750f1b487)

Also I have two more tests here with missing icons 

1. White svg, taken from logo of https://arxiv.org/   ![Paper](https://badgen.net/badge/arXiv/1234.5678/green?icon=https://static.arxiv.org/static/browse/0.3.4/images/arxiv-logo-one-color-white.svg)
```https://badgen.net/badge/arXiv/1234.5678/green?icon=https://static.arxiv.org/static/browse/0.3.4/images/arxiv-logo-one-color-white.svg```


2. Black svg, taken from https://simpleicons.org/   ![Another](https://badgen.net/badge/arXiv/9876.5432/blue?icon=https://simpleicons.org/icons/dotnet.svg)
```https://badgen.net/badge/arXiv/9876.5432/blue?icon=https://simpleicons.org/icons/dotnet.svg ```


Anyway I would like to thank you for the awesome badgen service
