### ISSUE TITLE
Inconsistent / incorrect coloring

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen.net#328]
I first noticed it on my failing travis badge, which is orange instead of red. Then when look over the badgen.net i've seen couple of other incorrect ones - DavidDM "out of date" is orange too.

We need to add failing travis example on the site.

edit: I've just seen the source that it intentionally sets it as orange for `failed/failing` why? This is inconsistent with the rest of the CIs that are showing red for failing. It shouldn't matter that there is "broken" and other statuses on the Travis side.

Same thing for the David DM - "out of date" is orange and only "insecure" is red. Both are almost the same thing anyway and equally need (red) attention.

**Comment by amio** [comment]
Forgot why it's `orange` for `failed/failing` in travis badge, I think it's a mistake :P

For david-dm badge, "out of date" is warning, "insecure" is alert, it make sense to use orange/red to distinguish between them.
