### ISSUE TITLE
GitHub release/tag is not perfect

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen.net#33]
More of a note to me.

Currently we get the "first in response array" tag/release.
The Babel example is perferct for showing the problem.

I think with `/github/release/owner/repo` we should show latest stable release/tag. In the case with Babel latest one happens to be a "prerelease", so it shows it in orange.

I'm thinking for this

- `/github/release/owner/repo` should show lastest stable release (e.g. Babel's v6), in blue
- `/github/release/owner/repo/prerelease` show latest prerelease

Or what about `/github/prerelease/owner/repo` for the prereleases and `/github/release` for the stable ones?

Perfect would be `/github/release` and `/github/prerelease`, because this will allow for static github badges like `/github/release/owner/repo/v1.2.3` ... which... actually, not make much sense because you can just `/badge/release/v1.2.3/color` ;d

**Comment by amio** [comment]
> Perfect would be /github/release and /github/prerelease, because this will allow for static github badges like /github/release/owner/repo/v1.2.3

Nice!

**Comment by olstenlarck** [comment]
> Nice!

Rethinking it, i don't like it.
I'm more for `/github/release/owner/repo` and `/github/release/owner/repo/prerelease`, because here the `prerelease` is like a modifier, which make sense to be there. It's optional, like the color is optional.

**Comment by amio** [comment]
😂That make sense too.

Further thoughts:
- `/github/release/owner/repo` better show the latest released item in github, as represent the "status" of repo
- `/github/release/owner/repo/stable` will stick to latest stable release,
- `/github/release/owner/repo/prerelease` shows latest prerelease

Overall, the `/github/release` means the latest release in the repo, or specific channel/tag.

**Comment by olstenlarck** [comment]
Oookey, great.

Only that: how you'll now "next release" :joy_cat:

**Comment by amio** [comment]
Ooops, github don't have a "next" release, that's npm specific 🤦‍♂️

**Comment by olstenlarck** [comment]
So this issue applies those ideas to npm badges too :laughing: 

- `/npm/v/micromatch` - the `latest` (default)
- `/npm/v/micromatch/latest` - same as above
- `/npm/v/ava/next` - the `next` tag

**Comment by amio** [comment]
Finally got this
![image](https://user-images.githubusercontent.com/215282/43364336-d3a63f74-934a-11e8-8f80-ac67488f92e5.png)

**Comment by olstenlarck** [comment]
:+1:

**Comment by amio** [comment]
Hmmm, maybe not. I thought that make it clear it's "latest" (not "some") tag. What's your idea?

**Comment by amio** [comment]
To me "release" feels like it's latest by default, but "tag"s feels all equal.
