### ISSUE TITLE
The query string combining color=purple & icon=codecov is not working consistently

### ISSUE THREAD

**Issue by dnl-brnr** [badgen/badgen.net#332]
The following url doesn't work with purple and the codecov icon...

`https://flat.badgen.net/codecov/c/github/dnl-brnr/vanilla-js?color=purple&icon=codecov`

![codecov](https://flat.badgen.net/codecov/c/github/dnl-brnr/vanilla-js?color=purple&icon=codecov) 

...but it works fine with other colors.

![codecov](https://flat.badgen.net/codecov/c/github/dnl-brnr/vanilla-js?color=blue&icon=codecov) ![codecov](https://flat.badgen.net/codecov/c/github/dnl-brnr/vanilla-js?color=red&icon=codecov) ![codecov](https://flat.badgen.net/codecov/c/github/dnl-brnr/vanilla-js?color=yellow&icon=codecov) ![codecov](https://flat.badgen.net/codecov/c/github/dnl-brnr/vanilla-js?color=green&icon=codecov)

However, for a different project, purple and the codecov icon _does_ work.

`https://flat.badgen.net/codecov/c/github/babel/babel?color=purple&icon=codecov`

![codecov](https://flat.badgen.net/codecov/c/github/babel/babel?color=purple&icon=codecov)

**Comment by styfle** [comment]
Looks like github cached a bad copy. Visiting the URL directly works: https://flat.badgen.net/codecov/c/github/dnl-brnr/vanilla-js?color=purple&icon=codecov

Adding an additional query string param might bust the cache:
https://flat.badgen.net/codecov/c/github/dnl-brnr/vanilla-js?color=purple&icon=codecov&d=20191209

**Comment by dnl-brnr** [comment]
Ahh! Good catch, I didn't think of that. It was cached in my browser as well. Thanks!
