### ISSUE TITLE
Support Snyk

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen.net#340]
It supports both regular and monorepos.

Basically that's their badge

```
https://snyk.io/test/github/badgen/badgen.net/badge.svg?targetFile=package.json
```

or for package from a monorepo

```
https://snyk.io/test/github/tunnckoCore/opensource/badge.svg?targetFile=@tunnckocore/utils/package.json
https://snyk.io/test/github/tunnckoCore/opensource/badge.svg?targetFile=packages/glob-cache/package.json
```

The sad thing is that it has only 200 tests per month, which isn't not on per repo basis but on per "target file" basis, which in case of a monorepo is almost nothing. Currently it counted 22 tests for me for mine single monorepo. In the pricing page it says it is "Unlimited tests for open source / public repos" but in the dashboard the range is to 200. So.. I guess we'll see. But anyway.

I'm still not sure if I woould use it at all. Instead I think to use Pnpm + lockfile-lint.

**Comment by amio** [comment]
I had an idea of creating a GitHub Action, which generates badges and push them to an orphan branch like 'badges', then you may reference them from github hosting.

Could be a nice companion to `lockfile-lint` and many other similar tools
