### ISSUE TITLE
Incorrect npm/types badge

### ISSUE THREAD

**Issue by KsRyY** [badgen/badgen.net#355]
When I access `badgen.net/npm/types/p-any`, badgen indicates that its type definition is shipped in `@types/p-any`, but `@types/p-any` is just a stub definition. p-any shipped its declaration within its package.

**Comment by amio** [comment]
@KsRyY You need to [including declarations in `package.json`](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) 😉

**Comment by KsRyY** [comment]
@amio So even though some packages shipped their declaration file, but if they didn't specify them in the package.json, badgen can't detect them. I understand. Thanks.

**Comment by amio** [comment]
@KsRyY Sorry, just notice there are two extra rules to locate type definition:

> Also note that if your package.json includes the "files" property the "types" property will be ignored. In that case you need to pass your main declaration file to the "files" property as well.

> Also note that if your main declaration file is named index.d.ts and lives at the root of the package (next to index.js) you do not need to mark the "types" property, though it is advisable to do so.

This should be supported.

**Comment by amio** [comment]
@KsRyY Thanks for reporting!
