### ISSUE TITLE
Support bitbucket/gitlab in LGTM badges

### ISSUE THREAD

**Issue by ghost** [badgen/badgen.net#356]
Currently, there is support only for GitHub repositories. However, GitLab and BitBucket repos exist with the prefix of /gl/ and /b/ instead of GitHub's /g/ on LGTM's API, so this should be a customisation option.

Example bitbucket LGTM: https://lgtm.com/projects/b/wegtam/bitbucket-youtrack-broker/?mode=list
Example gitlab LGTM: https://lgtm.com/projects/gl/nekokatt/hikari/?mode=list

**Comment by amio** [comment]
Yep, this should be supported, I think it was planned but forgotten later :D

@nekokatt Thanks for reminding!
