### ISSUE TITLE
Support GitHub milestone percentage

### ISSUE THREAD

**Issue by wopian** [badgen/badgen.net#357]
Milestones are kinda tucked away on GitHub - behind `Issues -> Milestones` and would be nice to be able to list the statuses of on-going projects from READMEs.

# Example

`/github/milestones/<repoOwner>/<repo>/<milestoneID>/<milestoneName>`
`/github/milestones/chrislgarry/Apollo-11/1/Comanche055` produces:
![](https://flat.badgen.net/badge/Comanche055/93%25?color=green)

![image](https://user-images.githubusercontent.com/3440094/74804839-51160580-52d9-11ea-9c5c-081ae3f4b7e4.png)

# API

REST https://developer.github.com/v3/issues/milestones/
GraphQL https://developer.github.com/v4/object/milestone/

**Comment by amio** [comment]
That's nice!
