### ISSUE TITLE
Support Tidelift badge

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen.net#359]
Which... is kind of interesting, because 1) it's not a check; 2) it's not a status, soo...
The question is _"Wat it is?!"_ :laughing: 

There is some "official" badge by them (@phated as one that I know and is part of @tidelift) that is redirecting to Shields (not very wise ;d) looking like `logo | lifted!` which... isn't exactly what I want and seems kind of meaningless to me.

![](https://tidelift.com/badges/package/pypi/setuptools-scm) `![](https://tidelift.com/badges/package/pypi/setuptools-scm)`
![](https://tidelift.com/badges/package/npm/formidable) `![](https://tidelift.com/badges/package/npm/formidable)`
![](https://tidelift.com/badges/package/npm/chalk) `![](https://tidelift.com/badges/package/npm/chalk)`
![](https://tidelift.com/badges/package/npm/bar-qxu-zaza) `![](https://tidelift.com/badges/package/npm/bar-qxu-zaza)`

What I'm  thinking is to get the status (or whatever it is) from github and show it on a badge. Recently I had failing tidelift status/check and thought to add one more badge to the already too many other badges - since I already am using separate "build" status/check badges for the separate OSes (#351), [as seen in `formidable`](https://github.com/node-formidable/formidable).

---

offtopic: I'm soon back to #351 and #352 for the updates and discussions.

**Comment by amio** [comment]
What is a tidelift status/check?

**Comment by tunnckoCore** [comment]
@amio as seen in commit and PRs statuses - see the PR details here https://github.com/node-formidable/formidable/pull/583 and commit status
![image](https://user-images.githubusercontent.com/5038030/75313425-6e148080-5865-11ea-85cf-d842940cc350.png)

**Comment by amio** [comment]
Added in #391 by @vladimyr , kudos to him!

**Comment by vladimyr** [comment]
> Added in #391 by @vladimyr , kudos to him!

Actually, here is what @tunnckoCore originally said about their _official_ badge:

> There is some "official" badge by them (@phated as one that I know and is part of @tidelift) that is redirecting to Shields (not very wise ;d) looking like `logo | lifted!` which... isn't exactly what I want and seems kind of meaningless to me.

and all I did is parse that redirect and serve correct badge from badgen.net. It doesn't do what @tunnckoCore proposed so this should probably be reopened 🤔

**Comment by amio** [comment]
Since it doesn't come with an official api, I guess this is the best we can do. What do you think? @tunnckoCore

**Comment by vladimyr** [comment]
Looking from that perspective you are probably right 👍

**Comment by tunnckoCore** [comment]
Probably yea. But I think that we can remove that `!` if we detect it's there. It's ugly and unnecessary, it doesn't make any sense.

**Comment by vladimyr** [comment]
> Probably yea. But I think that we can remove that `!` if we detect it's there. It's ugly and unnecessary, it doesn't make any sense.

We can't let that exclamation mark bug you → #397 😁
