### ISSUE TITLE
Color suggestion: teal

### ISSUE THREAD

**Issue by vonas** [badgen/badgen.net#360]
Hey there, I quite like  the color `teal` as you can see here:

[![shields.io badge](https://img.shields.io/npm/v/mermaid?color=teal&label=mermaid&logo=npm)](https://img.shields.io/npm/v/mermaid?color=teal&label=mermaid&logo=npm)

Would love to see it available!

**Comment by styfle** [comment]
Classic broken image 😆 

![image](https://user-images.githubusercontent.com/229881/75448185-b8b2fd00-5938-11ea-8fe8-1af80f5900cd.png)

That said, you can use any hex color like so https://badgen.net/npm/dm/now?color=55ccff

**Comment by vonas** [comment]
>Classic broken image laughing

I knew someone would comment that, haha.

Thank you for the response, I missed that!
