### ISSUE TITLE
Support Dynamic Badges - Discord

### ISSUE THREAD

**Issue by donavanbecker** [badgen/badgen.net#362]
Like Shields.io did here - https://shields.io/category/chat

**Comment by amio** [comment]
Looks like two more live badges to go, discourse and matrix.

**Comment by donavanbecker** [comment]
Can you do discord too?

**Comment by amio** [comment]
Nice to have, let's put it on the list. PR's welcome 🤗

**Comment by SuperSandro2000** [comment]
I would like to additionally request mastodon.

**Comment by donavanbecker** [comment]
[shields.io - discord](https://github.com/badges/shields/tree/fcf6678a127c9679b0d68284b860181c2580fe26/services/discord)

**Comment by amio** [comment]
Many thanks to @vladimyr !

**Comment by donavanbecker** [comment]
So awesome!!
