### ISSUE TITLE
how to use these

### ISSUE THREAD

**Issue by zilahir** [badgen/badgen.net#365]
I am having hard times understanding how to use this. For example if I want to add a dependabot live badge to a readme,

1) how to  connect it to the dependabot
2) how to add it to the readme

Maybe it's just me how is missing some fundamental knowledge, but i havent found any documentation or tutorial how to use this. 

Thanks!

**Comment by amio** [comment]
@zilahir To enable dependabot on a repo (for the badge to working), you need to login at https://app.dependabot.com/ then add it manually, or add a [`.dependabot/config.yml`](https://dependabot.com/docs/config-file/) file to the repo. Then you may include the badge in your repo like [this PR](https://github.com/thepracticaldev/dev.to/pull/3268).

It's a bit complicated for private repo, here's a doc for it https://badgen.net/dependabot

**Comment by zilahir** [comment]
@amio thanks for the reply! :) maybe i am stupid or blind, or both, but honestly, i cant find within dependapot, where to add the badges. :(

**Comment by zilahir** [comment]
@amio thanks for the reply!! :)
