### ISSUE TITLE
Error badges on chorme web store

### ISSUE THREAD

**Issue by crimx** [badgen/badgen.net#373]
![image](https://user-images.githubusercontent.com/6882794/79309447-e4ac3100-7f2c-11ea-814c-c04202ef8d72.png)

**Comment by amio** [comment]
@crimx Thanks for reporting

**Comment by andyrichardson** [comment]
@amio is this fix still to be released? I'm still getting 5xx responses

### Examples

[store listing](https://chrome.google.com/webstore/detail/urql-devtools/mcfphkbpmkbeofnkjehahlmidmceblmm)
[badge link](https://badgen.net/chrome-web-store/v/mcfphkbpmkbeofnkjehahlmidmceblmm?color=fbbc07)

### Screenshots

![Screenshot 2020-05-07 at 15 07 48](https://user-images.githubusercontent.com/10779424/81304162-97773700-9074-11ea-8941-611f5e9947e3.png)
![Screenshot 2020-05-07 at 15 08 03](https://user-images.githubusercontent.com/10779424/81304166-9940fa80-9074-11ea-8107-d11a7601d8a6.png)

**Comment by amio** [comment]
@andyrichardson it was fixed and released, it's broken again. Here's the fix https://github.com/simov/chrome-webstore/pull/2

**Comment by crimx** [comment]
Instead of waiting PR being merged every time it seems like you can just pass the `version` as function argument.

Also the `version` can be teased out directly from the html. How about adding a script that checks the version daily? I can help if you want to give it a spin.

**Comment by amio** [comment]
> pass the `version` as function argument

👍

> adding a script that checks the version daily?

Badgen is stateless, we cannot store/cache this version info. We could make it a standalone api with cdn cache, like a https://latest-chrome-webstore-api-version.now.sh just responses `20200420` , but I guess two serial requests for generating a badge would hurt some performance and stability.

**Comment by crimx** [comment]
Is there a way to be notified when the webstore api is broken? So that the version can be updated with  Badgen.

**Comment by amio** [comment]
Thought about making a cron job with GitHub Actions to check api availability, a failed execution would leave a notification on GitHub.

PS, we can even make a status page base on this 😂

**Comment by crimx** [comment]
That should work. Though ideally the Action should just update the `version` automatically.

I've submitted a [PR](https://github.com/simov/chrome-webstore/pull/3) to chrome-webstore.

**Comment by simov** [comment]
Published the new method in v1.4.0 as `.version()` :tada:
