### ISSUE TITLE
GitHub "combined checks (default branch)" not working when the default branch is not "master"

### ISSUE THREAD

**Issue by cedx** [badgen/badgen.net#409]
On my GitHub projects, I've renamed my "master" branches to "main": "main" is the new default branch (and "master" was deleted accordingly).
Since this change, the badge "GitHub combined checks (default branch)" does not work anymore and displays a 522 error.

An example :
https://badgen.net/github/checks/cedx/enum.php

Now, I must add "/main" to the badge URL to fix it:
https://badgen.net/github/checks/cedx/enum.php/main

**Comment by styfle** [comment]
I'm having a similar issue but adding `main` doesn't seem to work.

- GitHub 422: https://badgen.net/github/checks/styfle/packagephobia
- Badgen Error: https://badgen.net/github/checks/styfle/packagephobia/main

**Comment by amio** [comment]
@cedx  I'm not sure we would change default branch from "master" to "main", mainly because it's a breaking change. Besides, I think the naming of default branch more depends on git, other than GitHub. Even on GitHub side, a new project's welcome page still recommending `git push -u origin master`.

@styfle [That](https://badgen.net/github/checks/styfle/packagephobia/main)'s a problem, let me check on it

**Comment by wopian** [comment]
GitHub's API provides the default branch. It's more expensive than just blindly calling `master` but it's going to work 100% of the time. 

REST v3 https://developer.github.com/v3/repos/#response-5 (`default_branch`, string)
GraphQL v4 https://developer.github.com/v4/object/repository/#fields (`defaultBranchRef`, object)

**Comment by cedx** [comment]
@amio I'm fine with adding `/main` to my badges. It's just that the wording is misleading: `combined checks (default branch)` should probably renamed to `combined checks (master branch)`, and the fact that we can add the desired branch to the URL should be mentioned on the homepage (i.e. add `combined checks (branch)`).

**Comment by styfle** [comment]
FYI, GitHub plans to use `main` in the future for default branch: https://github.com/github/renaming

So assuming `master` is going to become increasingly more rare in the future

https://github.com/badgen/badgen.net/blob/d190f787b8843155f4e04befcc23aac786c3fcb4/api/github.ts#L99

**Comment by amio** [comment]
We might "upgrade" all github badges to use real "default" branch, as @wopian [mentioned](https://github.com/badgen/badgen.net/issues/409#issuecomment-651793871).

The only use case broken by this change is when someone use `/github/checks/:scope/:repo` for master branch specifically, while setting default branch to something else. It's rare I guess 😄
