### ISSUE TITLE
Add Badge for Github Dependabot

### ISSUE THREAD

**Issue by libinvarghese** [badgen/badgen.net#419]
Since Github is supporting Dependabot [natively](https://docs.github.com/en/github/administering-a-repository/about-github-dependabot-version-updates), which is not compatible with the [Dependabot App](https://badgen.net/dependabot)

It would be great to have a badge to know if Dependabot is active on the repo.

eg: ![Dependabot](https://badgen.net/badge/Dependabot/Active/green)

**Comment by amio** [comment]
Guess we may sunset the standalone dependabot badge at sometime.
