### ISSUE TITLE
Support flat versions of recently added icon badges

### ISSUE THREAD

**Issue by jmiskinis** [badgen/badgen.net#430]
Hey! I noticed that recently added icon badges (e.g. Wiki) are not available in flat.badgen.net. Is this intentional or an oversight? Thanks

**Comment by amio** [comment]
There's a failure in deployment task, https://github.com/badgen/badgen.net/runs/1101565495
I'll take a look at it ✅

**Comment by jmiskinis** [comment]
Icons are now available. Thanks for taking care of this!
