### ISSUE TITLE
npm License not working for scoped packages

### ISSUE THREAD

**Issue by cedx** [badgen/badgen.net#436]
The URL pattern to use for a npm License badge is:
`https://badgen.net/npm/license/<package>`

It works fine for top-level packages (e.g. `lodash`) but it does not seem to work with scoped packages (e.g. `@babel/core`):

https://badgen.net/npm/license/@babel/core => unknown license
https://badgen.net/npm/license/%40babel/core => 403 error
https://badgen.net/npm/license/%40babel%2Fcore => unknown license

**Comment by amio** [comment]
@cedx Thanks for reporting

**Comment by amio** [comment]
It looks like npm removed the `license` field from their package meta api
