### ISSUE TITLE
Coveralls coverage: NaN%

### ISSUE THREAD

**Issue by cedx** [badgen/badgen.net#437]
When the coverage of a project is very low, less than 1%, the Coveralls badge shows `NaN%`:
https://badgen.net/coveralls/c/github/cedx/gitea.hx => ![Coveralls](https://badgen.net/coveralls/c/github/cedx/gitea.hx)

On Coveralls, the project has a coverage of 0.685% (see https://coveralls.io/github/cedx/gitea.hx).
In this case, the official badge is rounded up to 1%:
https://coveralls.io/repos/github/cedx/gitea.hx/badge.svg => ![Coveralls](https://coveralls.io/repos/github/cedx/gitea.hx/badge.svg)

**Comment by amio** [comment]
Good catch, thanks @cedx
