### ISSUE TITLE
Using `%` as text breaks the badges

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen.net#447]
Hey, I just noticed that my custom badges for code coverage shown in percentage are broken.

```
https://badgen.net/badge/coverage/7.79%25/red
```

When remove the `%` it works. The `%25` is for the `%` symbol. 

Any ideas how to achieve that? I guess it's something with the encodings.

**Comment by wopian** [comment]
Seems to be displaying correctly for me 
![image](https://user-images.githubusercontent.com/3440094/100394469-2493d480-3035-11eb-89e7-3f6dee3543f5.png)

**Comment by amio** [comment]
Same as @wopian 

@tunnckoCore Is it got unescaped before treating as image src?

**Comment by tunnckoCore** [comment]
Hm. Now it works. That was weird :laughing:
