### ISSUE TITLE
Packagist: outdated pre version

### ISSUE THREAD

**Issue by f3l1x** [badgen/badgen.net#448]
Hi, thank you for awesome webservice.

I've just came across some packagist PHP version behaviour. I want to show PHP version for upcoming version, let say untagged master branch.

-----

He is how it works on badgen.net.

**v0.6**

Here is latest tagged version, it works correctly.

- It shows `^7.2`
- `https://badgen.net/packagist/php/contributte/forms/latest`
- ![](https://badgen.net/packagist/php/contributte/forms/latest)

**dev-master**

Here is untagged dev-master version, it doesn't work correctly, from my point of view. 

- It shows `^7.2` instead of `>=7.2`
- `https://badgen.net/packagist/php/contributte/forms/pre`
- ![](https://badgen.net/packagist/php/contributte/forms/pre)
- `https://badgen.net/packagist/php/contributte/forms/master`
- ![](https://badgen.net/packagist/php/contributte/forms/master)
- `https://badgen.net/packagist/php/contributte/forms/dev-master`
- ![](https://badgen.net/packagist/php/contributte/forms/dev-master)

-----

According to packagist, it shows correct data.

**v0.6**

![image](https://user-images.githubusercontent.com/538058/100448722-08367d00-30b3-11eb-8f54-1717864c8eeb.png)

**dev-master**

<img width="1160" alt="Screenshot 2020-11-27 at 13 18 30" src="https://user-images.githubusercontent.com/538058/100449050-8e52c380-30b3-11eb-84b8-e1398df00e93.png">

-----

According to packagist JSON endpoint, it shows correct data.

<img width="844" alt="https___packagist_org_packages_apitte_core_json" src="https://user-images.githubusercontent.com/538058/100449011-7e3ae400-30b3-11eb-9666-61c1e4f261a7.png">

-----

Am I doing something wrong? Thank you for you time.

**Comment by amio** [comment]
@f3l1x Did you expect it to show `>=7.2`?

![image](https://user-images.githubusercontent.com/215282/100969351-f3a02c00-356d-11eb-8e69-4f99ed725b62.png)

**Comment by f3l1x** [comment]
Hi, yup, in the meantime we release a new version 🤦  So the example is outdated, I have updated initial comment to other package, where it is not working from my point of view.

**Comment by wopian** [comment]
Packagist links:

https://packagist.org/packages/contributte/forms#dev-master
https://packagist.org/packages/contributte/forms#v0.4.0
https://repo.packagist.org/p/contributte/forms.json

**Comment by amio** [comment]
Made a fix #451 
Preview at https://badgennet-git-fix-packagist-channel.badgen.vercel.app/packagist

- `https://badgennet-git-fix-packagist-channel.badgen.vercel.app/packagist/php/contributte/forms/pre`
- ![](https://badgennet-git-fix-packagist-channel.badgen.vercel.app/packagist/php/contributte/forms/pre)
- `https://badgennet-git-fix-packagist-channel.badgen.vercel.app/packagist/php/contributte/forms/master`
- ![](https://badgennet-git-fix-packagist-channel.badgen.vercel.app/packagist/php/contributte/forms/master)
- `https://badgennet-git-fix-packagist-channel.badgen.vercel.app/packagist/php/contributte/forms/dev-master`
- ![](https://badgennet-git-fix-packagist-channel.badgen.vercel.app/packagist/php/contributte/forms/dev-master)

**Comment by f3l1x** [comment]
Looks good to me.
