### ISSUE TITLE
Github Status vs Github Checks

### ISSUE THREAD

**Issue by f3l1x** [badgen/badgen.net#471]
Hi, I am little confused what check and status is.

I have this repository (https://github.com/apitte/debug) and master branch is failing.

![image](https://user-images.githubusercontent.com/538058/103366328-a3f84600-4ac2-11eb-8bf9-580d88921703.png)

What should I use to display Github Actions badge? What is the difference between status and check?

Thank you very much.

-----

- `https://badgen.net/github/status/apitte/debug`

![image](https://user-images.githubusercontent.com/538058/103366295-84f9b400-4ac2-11eb-94cd-cece2bff8432.png)

- `https://badgen.net/github/checks/apitte/debug`

![image](https://user-images.githubusercontent.com/538058/103366309-90e57600-4ac2-11eb-8641-83983c5fd559.png)

**Comment by wopian** [comment]
`status` and `checks` are two types of status checks (...yes) provided by GitHub. Their docs explain the differences at https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-status-checks#types-of-status-checks-on-github

**Comment by f3l1x** [comment]
Thank you @wopian. If I get it right I should use `checks` to displays Github Action status, right?

**Comment by f3l1x** [comment]
For this repository (https://github.com/contributte/translation). I am getting badge error. 

- `https://badgen.net/github/checks/contributte/translation`
    ![image](https://user-images.githubusercontent.com/538058/103442969-db015f80-4c5a-11eb-9386-9fba34ae32b6.png)



Do you think it's because of `coverage/coveralls` failing?

![image](https://user-images.githubusercontent.com/538058/103442934-a4c3e000-4c5a-11eb-8213-7f30ae946949.png)

**Comment by amio** [comment]
@f3l1x That's a bug, here's the fix #474

**Comment by amio** [comment]
https://badgennet-git-fix-github-skipped-check.badgen.vercel.app/github/checks/contributte/translation
![](https://badgennet-git-fix-github-skipped-check.badgen.vercel.app/github/checks/contributte/translation)

**Comment by f3l1x** [comment]
Looks good to me.
