### ISSUE TITLE
Release Tag data is wrong

### ISSUE THREAD

**Issue by rajat19** [badgen/badgen.net#484]
I am using badgen.net to get latest tag for [VS Code](https://github.com/microsoft/vscode) repo

[![Tag Latest](https://badgen.net/github/tag/microsoft/vscode)](https://github.com/microsoft/vscode/tags)
```
[![Tag Latest](https://badgen.net/github/tag/microsoft/vscode)](https://github.com/microsoft/vscode/tags)
```

the tag shown is incorrect 
it should have been `1.52.1` (as of 31 jan 2021)
Check https://github.com/microsoft/vscode/tags

The tag your badge displays is very very old (2017 tag)
https://github.com/microsoft/vscode/releases/tag/translation/20172701.01

Am I using the badge incorrectly or is there some other issue ?

**Comment by vladimyr** [comment]
Thank you for your report @rajat19 

Your usage is correct. There is a bug in the tag retrieval GraphQL query which will get fixed as soon as #485 gets merged.
