### ISSUE TITLE
Emoji as icon?

### ISSUE THREAD

**Issue by d33tah** [badgen/badgen.net#518]
I love this project! The only thing I need to make my badge perfect is to be able to add an emoji (e.g. via codepoint) that would be put in place of the icon. Is there a way you could add this? In my case, the emoji I'm looking for is a red heart.

**Comment by wopian** [comment]
You can put the emoji in the label

E.g `?label=%E2%99%A5%EF%B8%8F` for ♥️

**Comment by amio** [comment]
![](https://badgen.net/badge/%E2%99%A5/yo)
https://badgen.net/badge/%E2%99%A5/yo

**Comment by qoomon** [comment]
![](https://badgen.net/badge/icon/is%20all%20around%20me/blue?label&icon=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA%2FwD%2FAP%2BgvaeTAAAD1UlEQVRoge2ZXWhbZRjH%2F8%2BbLUvOSTq2iuDFGMgY80pwrGniTbBphdlueOHczUB2UXe1u00EoYOxsukQP6CKiIIMcQTRrWLdWeeCH0vSmbEKoqsXIrsobJRC25O0TfM%2BXtQT89Wej5zkqOR39Zznfc%2F7%2FP9vTtLzPgU6dOjwn4ac3vjw0NPhrSXasl2Z1yn5y6qbouxg2cDCQHQfgY%2BC8SwBTwDY%2FvfQGoDfAdwill8oO3Z%2FQ8lkaaN1HsTjoaC%2FMEiSBkF4EsBeAH4AyyDMAHyXJV0J6TRB6XShaQMLfT17hU%2BMgHEUgDB1ynyPBY2EtczlqnQ0GsyHcIrBJwF0m64DmmXms6H54oeUyxUdGVjqjxwD6H0AinnBmoUJny%2F7%2BHj3RHZB74sdYCEvYX237TLtK4nDwW9v%2FdmwzkZ3LfVHRgF61UHByuV%2FAuQ7TjehggdC0JByLT1VV6HRbL2%2F9wQD7zVRsBXM%2BUgeCGpTf1Qm6wzkE5FeSfQjrDzv7YZxR10LRCiVWjNSonocJIners3%2FayA8lfcXjlenKtATkcNM9GV7VdmFZtXitscplVoGanda0DFPNNmCH8v7VxLGVdkAx%2BMBZhz0RpQ9WMrnjbhsYMm%2FugdA0BNFdiHqMULxT8B7vFHjAMZuIywbkJABb9Q4gBDmeDwAVH4Ckhe9U2SblfpfIZ%2BY9UyOfeaMoGxA6do1DWDeEzn2yRlB2QAlkyUCbnqjxx4MvmbE1X%2FIiD5uuxr7FH0krxoXVQaUWPprADNtl2SPTxXt9n3josoAnYFk4pH2a7LMqpRytDJR99YZ1rKfAfxd%2BzRZh4GLXTemqp6Qhq%2FNzHQCQL4tqqzCfC8UKJ6rTTc0EJ7M%2FMrEp1qvyjIFMI7QeK5uUzc8uIS17BiIP2mtLkswwMOhG9mfGw1uevJSfTuHwfR9a3RZg4DXQtezlzYa39QATUysFBTxHAE%2FuC%2FNHCacU69nRjebY6kzx0P7FX3ZPw7wM%2B5IMy8J5tOhyexFs4mWW4s8tF%2FRV7ZeASNhPrspSkQ0rGrpj6xMttx9oPFcXl0NDAFo5evGHCQNWhUPOOxO6wORYWZ6F%2BtNWbe47SP5Ym3jygxH%2FR9Vy34ghUwA5MYZggG8rhYDMbvigSb%2BPwAAC3093UKIMQBHHC4xw4yXw5OZlFMNTRkwWOyPvkDgMQCPWLylCOBNtRg4YxwNneKKAQBYHIg9SizPA3jJZN1xSXS6S0v%2F5kZd1wwY5PtiUSnkWwB6aoammPFKM49LI1w3YLCU6E2A%2BA0C6SBcULTMV7T%2Bhe3QoUOH%2FxF%2FAcKHNQNE3QZCAAAAAElFTkSuQmCC)
