### ISSUE TITLE
Docker badges report internal server error

### ISSUE THREAD

**Issue by akloeckner** [badgen/badgen.net#527]
Hey there,

I was considering badgen.net for my badges and realized, your Docker badges seem to be down. See example (from the website) here: https://badgen.net/docker/pulls/library/ubuntu .

It reports
```
500: INTERNAL_SERVER_ERROR
Code: INTERNAL_FUNCTION_NOT_FOUND
ID: cdg1::zggk9-1621928081006-d95a9927991c
```

I thought, I'd report here, to make sure you are aware of it...

Cheers!

**Comment by akloeckner** [comment]
Possible duplicate of #443, just from Germany this time?

**Comment by tennox** [comment]
![Screenshot from 2021-11-11 01-21-40](https://user-images.githubusercontent.com/2084639/141214509-35e3e24b-f2ee-4774-bd06-fcc177d75514.png)

**Comment by emmercm** [comment]
Also confirming that layers have almost never worked for me, e.g.: https://github.com/emmercm/docker-libtorrent/blob/5bef5fe56c551a8a579ef13dfe049e6dc1344cb7/README.md

**Comment by amio** [comment]
It seems some temporary issue, it's fine now
