### ISSUE TITLE
Badges for GitHub repo/pkg dependents are broken

### ISSUE THREAD

**Issue by wopian** [badgen/badgen.net#528]
The following two badges are currently broken and return `invalid` for any repository.

`https://flat.badgen.net/github/dependents-repo/micromatch/micromatch` 
![](https://flat.badgen.net/github/dependents-repo/micromatch/micromatch)

`https://flat.badgen.net/github/dependents-pkg/micromatch/micromatch` 
![](https://flat.badgen.net/github/dependents-pkg/micromatch/micromatch)

**Comment by amio** [comment]
Seems the regex is outdated, fixed in #532

**Comment by 75lb** [comment]
thanks for the fix but If this is going to break everytime Github changes their code it's a non-starter in my opinion

**Comment by amio** [comment]
@75lb A better approach is definitely welcome!

**Comment by 75lb** [comment]
Apparenty this schema preview exposes the repo dependency graph, i'll have a look later.. haven't confirmed yet.
https://docs.github.com/en/graphql/overview/schema-previews#access-to-a-repositories-dependency-graph-preview

**Comment by wopian** [comment]
I think it would be better to wait for those members to hit the stable GraphQL API first. 

Otherwise I feel it would be just as flimsy as the current HTML scrapping - with potential unannounced breaking changes to the preview schema breaking the badges
