### ISSUE TITLE
Unable to access domain in china, it's posibble to replace dns record

### ISSUE THREAD

**Issue by shfshanyue** [badgen/badgen.net#529]
In china，IP address 76.76.21.21 cannot be accessed. Using vercel, it can be replaced by `76.223.126.88` or `cname.vercel-dns.com` like `carbon`。

``` bash
$ dig +short badgen.net 
76.76.21.21
```

``` bash
$ dig +short carbon.now.sh
76.223.126.88
$ dig +short devtool.tech 
cname.vercel-dns.com.
76.223.126.88
```

**Comment by amio** [comment]
@shfshanyue Maybe a temporary issue? It's fine when I checked from Shanghai Unicom.

**Comment by shfshanyue** [comment]
@amio  It does not work in Beijing and maybe cname record is better than a record.

**Comment by amio** [comment]
@shfshanyue is this issue resolved?
