### ISSUE TITLE
flat badgen.net builder for github workflows

### ISSUE THREAD

**Issue by Ismoh** [badgen/badgen.net#543]
I love badgen.net and the flat builder, but I am wondering, if there is a way to generate a workflow badge like github offers, but in a flat style?

Githubs workflow badge:
[![Ubuntu Lua Unit Testing](https://github.com/Ismoh/NoitaMP/actions/workflows/ubuntu-latest-lua-unit-testing.yml/badge.svg)](https://github.com/Ismoh/NoitaMP/actions/workflows/ubuntu-latest-lua-unit-testing.yml)
It's ugly in my opinion :(

Maybe something like shields.io ?style=flat-square:
[![flat-square](https://shields.io/badge/style-flat--square-green?logo=appveyor&style=flat-square)](https://shields.io/badge/style-flat--square-green?logo=appveyor&style=flat-square)

**Comment by amio** [comment]
You mean this builder? https://badgen.net/builder
For flat style, you may use https://flat.badgen.net/builder

**Comment by Ismoh** [comment]
That's the on I mean, but there are no worklfow badges, is this correct?

**Comment by Ismoh** [comment]
I am using shields.io
