### ISSUE TITLE
Chrome web store badge doesn't always show the "K"

### ISSUE THREAD

**Issue by bokub** [badgen/badgen.net#559]
Hello @amio !

This [badge](https://flat.badgen.net/chrome-web-store/users/hpoiflhmfklhfcfpibmdmpeonphmdbda) says "4" when I open it in my browser, when it's supposed to say "4K".

![image](https://user-images.githubusercontent.com/17952318/179905313-3a9f9188-cdba-4fe9-88d5-9f266de8c99e.png)
However, it says "4K" when I include it on GitHub using markdown, which is very weird...

![image](https://user-images.githubusercontent.com/17952318/179906513-688ed87a-f8ba-47d7-ab62-b56e5e240c5a.png)

____

Here is the dynamic badge. Right now, I see "4K", but maybe it will say "4" in a few hours 🤷 
 ![badge](https://flat.badgen.net/chrome-web-store/users/hpoiflhmfklhfcfpibmdmpeonphmdbda)

Do you have an explanation for this weird behavior?
Thanks!

**Comment by amio** [comment]
That's strange 🤔

**Comment by bokub** [comment]
Yes, very strange!

Do you also see "5" when you open the link?

**Comment by amio** [comment]
I can see the "5K" in https://flat.badgen.net/chrome-web-store/users/hpoiflhmfklhfcfpibmdmpeonphmdbda

**Comment by bokub** [comment]
![Screenshot_20220827_111711_com.android.chrome.png](https://user-images.githubusercontent.com/17952318/187023889-fc9e50a9-da40-425a-8b2a-9b22d36fdd78.png)

So weird, I see 5.
I'm on mobile, on a different network since last time...

**Comment by bokub** [comment]
Hello !

It looks like this bug it still going on, and it's now visible directly on the homepage of [badgen.net](https://badgen.net), where I can read "200 users", while there are actually [200k](https://chrome.google.com/webstore/detail/markdown-viewer/ckkdlimhmcjmikdlpkmbgfkaikojcbjk) users

![image](https://user-images.githubusercontent.com/17952318/217846517-5974ec37-6e95-46de-b128-89a729d89bdd.png)

The issue might be coming from [webextension-store-meta](https://github.com/awesome-webextension/webextension-store-meta), which looks abandonned by its maintainer

**Comment by bokub** [comment]
Oh, I think I understand now ! The result seems to depend on the request location

For example, 
- with a proxy based in New York, I [see 200K](https://proxy-nyc.hidemyass-freeproxy.com/proxy/en-ww/aHR0cHM6Ly9iYWRnZW4ubmV0L2Nocm9tZS13ZWItc3RvcmUvdXNlcnMvY2trZGxpbWhtY2ptaWtkbHBrbWJnZmthaWtvamNiams)
- with a proxy based in Francfort, I [see 200](https://proxy-fra.hidemyass-freeproxy.com/proxy/en-ww/aHR0cHM6Ly9iYWRnZW4ubmV0L2Nocm9tZS13ZWItc3RvcmUvdXNlcnMvY2trZGxpbWhtY2ptaWtkbHBrbWJnZmthaWtvamNiams)

Maybe the chrome web store response depends on the location, and this is not properly handled by [webextension-store-meta](https://github.com/awesome-webextension/webextension-store-meta) for European countries...

**Comment by bokub** [comment]
As a temporary fix, I created a runkit endpoint to fix this badge:

https://runkit.com/bokub/chrome-web-store-users

Example badge using this endpoint: ![Chrome users](https://badgen.net/runkit/bokub/chrome-web-store-users/hpoiflhmfklhfcfpibmdmpeonphmdbda)
URL: `https://badgen.net/runkit/bokub/chrome-web-store-users/hpoiflhmfklhfcfpibmdmpeonphmdbda`

**Comment by amio** [comment]
Thanks @bokub !
I'm doing an refactor https://github.com/badgen/badgen.net/pull/579 , I'll integrate the fix in the migration.

**Comment by amio** [comment]
This should get fixed by now, thanks @bokub !
