### ISSUE TITLE
Suggested Icon: Snyk

### ISSUE THREAD

**Issue by emmercm** [badgen/badgen.net#565]
Hi Badgen team,

I'm excited to learn that Snyk support was added in https://github.com/badgen/badgen.net/issues/340, it will help me standardize my badges.

However, I'd love to add a Snyk icon to my badge, e.g. `https://badgen.net/snyk/badgen/badgen.net?icon=snyk`.

Please let me know if there's a better way to request this. Thanks!

**Comment by zhongfly** [comment]
https://github.com/badgen/badgen-icons

**Comment by emmercm** [comment]
Ah sorry about that, thank you @zhongfly , opened at https://github.com/badgen/badgen-icons/issues/48.
