### ISSUE TITLE
Icon Support

### ISSUE THREAD

**Issue by CredenceHamby** [badgen/badgen.net#570]
Are https://simpleicons.org/ icons not supported, or am I just doing it wrong? Example "&icon=steam"

**Comment by redzioch** [comment]
It seems, that it does not work anymore. See the last comment in mentioned issue: https://github.com/badgen/badgen.net/issues/325#issuecomment-1586108416

**Comment by amio** [comment]
Oh it's missed during a refactor recently, I'll add it back
