### ISSUE TITLE
Some hackage badges just display "badgen error"

### ISSUE THREAD

**Issue by andreasabel** [badgen/badgen.net#585]
Some of my hackage badges display "badgen error"; I do not see a pattern. E.g.
- `<img src="https://badgen.net/hackage/v/BNFC"/>` <img src="https://badgen.net/hackage/v/BNFC"/>

**Comment by bangank36** [comment]
Here is the list of broken badge as I see on the homepage

| Badge | Screenshot |
|-------|------------|
|  [Github](https://badgen.net/#github)     |      <img width="792" alt="image" src="https://user-images.githubusercontent.com/10071857/217705324-10d81e22-5f62-4b31-925d-0ca8f1d466a3.png">      |
|  [CRAN](https://badgen.net/#cran)     |      <img width="506" alt="image" src="https://user-images.githubusercontent.com/10071857/217705588-0982c900-3eea-45e2-8906-548ac6ba9365.png">      |
|  [winget](https://badgen.net/#winget)     |      <img width="465" alt="image" src="https://user-images.githubusercontent.com/10071857/217705660-e25a9c7d-052e-40ae-a65a-2c9837420550.png">      |
|  [CircleCI](https://badgen.net/#circleci)     |      <img width="628" alt="image" src="https://user-images.githubusercontent.com/10071857/217705790-e38ed895-1ef0-4132-a5fb-0e3f951133ea.png">      |
|  [LGTM](https://badgen.net/#lgtm)     |      <img width="604" alt="image" src="https://user-images.githubusercontent.com/10071857/217705906-060c528c-28fe-487e-82e3-179026c2f98f.png">      |
|  [PeerTube](https://badgen.net/#peertube)     |      <img width="1095" alt="image" src="https://user-images.githubusercontent.com/10071857/217706001-da922522-48ed-41a1-a6a8-912e7d737ccb.png">     |
|  [Twitter](https://badgen.net/#twitter)     |      <img width="576" alt="image" src="https://user-images.githubusercontent.com/10071857/217706114-6cb0c0e5-0d45-43ab-9598-9cde802d0dc2.png">      |
|  Static     |      <img width="627" alt="image" src="https://user-images.githubusercontent.com/10071857/217706216-f8b53cb4-b3d5-43f3-956e-2377ace41f2f.png">      |

**Comment by iccicci** [comment]
Travis CI badge is broken too since some weeks

**Comment by TheSpiritXIII** [comment]
I've been seeing random failures. Refreshing usually resolves, e.g. I just tried to load the homepage and get these failures among others:
```
badgen.net/:7     GET https://badgen.net/badge/color/yellow/yellow 500
badgen.net/:7     GET https://badgen.net/badge/color/grey/grey 500
```

I don't see a clear reason the basic badges should be failing.

**Comment by accetto** [comment]
I mostly get errors by these two kinds of requests:

```html
https://badgen.net/github/open-issues/accetto/ubuntu-vnc-xfce-g3?icon=github&label=open%20issues
https://badgen.net/github/last-commit/accetto/ubuntu-vnc-xfce-g3?icon=github&label=last%20commit
```

**Comment by iccicci** [comment]
I'm afarid badgen.net is simply no longer supported.
Anyone knows an alternative service?

**Comment by LimitlessGreen** [comment]
> I'm afarid badgen.net is simply no longer supported. Anyone knows an alternative service?

Sure: https://shields.io
