### ISSUE TITLE
[idea] range for pypi python versions

### ISSUE THREAD

**Issue by jdknight** [badgen/badgen.net#657]
Python packages may have a large version set supported. For example:

![image](https://github.com/badgen/badgen.net/assets/1834509/c238db1d-d05d-4a5e-b870-cc5530448246)

It may be nice to identify a range for packages that define a sequence of versions. For example (mockup):

![image](https://github.com/badgen/badgen.net/assets/1834509/99a3f47b-eb50-441c-9711-4c0ff95a24c2)

No worries if not desired.

**Comment by amio** [comment]
The shorter one is more eye pleasing.
I think we can use static badge for this case, if it's a range, then it usually doesn't need update frequently
https://badgen.net/static/python/2.7%20%7C%203.4-3.12

**Comment by jdknight** [comment]
Ah ~ static badge problem makes more sense than trying to support a range automatically (since long interpreter sets are most likely a rarity). Thanks for the suggestion. 🙇
