### ISSUE TITLE
Wrong number of chrome web store users

### ISSUE THREAD

**Issue by bokub** [badgen/badgen.net#660]
Hi,

This looks like #559, but it's a little bit different I think

The number of chrome webstore users **is divided by 1000**, for example, this shows "200" instead of "200 k": 
![badge](https://badgen.net/chrome-web-store/users/ckkdlimhmcjmikdlpkmbgfkaikojcbjk)

I tried to use a US-based proxy, but [the result](https://us6.proxysite.com/process.php?d=pARpKtSB0Gg7TL2UVgGToRihfTAt4VhWMC8%2BDwpFd4321uBrfj9QGkHIuUlUtzyIfda5yhivTMV9YZqILYpoxsKjViiQdA%3D%3D&b=1&f=norefer) is the same this time

|Chrome web store|badgen.net|
|---|---|
| ![image](https://github.com/badgen/badgen.net/assets/17952318/45eac530-24f2-4243-91e9-98f6ec51ab75) | ![image](https://github.com/badgen/badgen.net/assets/17952318/b844333f-330f-420c-bb96-cc91d48fd270) |

**Comment by amio** [comment]
Glad to see you back @bokub !

**Comment by amio** [comment]
@bokub Just updated the webextension-store-meta package in https://github.com/badgen/badgen.net/pull/671
Seems the `price` is no longer supported, just marked that badge as deprecated.
